language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t jeonghanchoi/docker-react -f Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-094208113353"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
